package de.fxdiagram.examples.lcars;

import com.mongodb.DBObject;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.CachedDomainObjectDescriptor;
import de.fxdiagram.core.model.DomainObjectProvider;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.examples.lcars.LcarsModelProvider;

@ModelNode
@SuppressWarnings("all")
public class LcarsEntryDescriptor extends CachedDomainObjectDescriptor<DBObject> {
  public LcarsEntryDescriptor(final String dbId, final String name, final LcarsModelProvider provider) {
    super(null, dbId, name, provider);
  }
  
  @Override
  public DBObject resolveDomainObject() {
    DomainObjectProvider _provider = this.getProvider();
    return ((LcarsModelProvider) _provider).<Object>resolveDomainObject(this);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public LcarsEntryDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
}
