package de.fxdiagram.examples.lcars;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.lcars.LcarsModelProvider;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class LcarsConnectionHandle extends DomainObjectHandleImpl {
  public LcarsConnectionHandle(final String fieldName, final LcarsModelProvider provider) {
    super(fieldName, fieldName, provider);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public LcarsConnectionHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
