package de.fxdiagram.examples.lcars;

import com.mongodb.DBObject;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.lcars.LcarsModelProvider;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class LcarsEntryHandle extends DomainObjectHandleImpl {
  public LcarsEntryHandle(final String dbId, final String name, final LcarsModelProvider provider) {
    super(dbId, name, provider);
  }
  
  public Object getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((DBObject) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public LcarsEntryHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
