package de.fxdiagram.examples.ecore;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.ecore.EcoreDomainObjectProvider;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.xtext.xbase.lib.Extension;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class EClassHandle extends DomainObjectHandleImpl {
  public EClassHandle(final EClass eClass, @Extension final EcoreDomainObjectProvider provider) {
    super(provider.getId(eClass), provider.getFqn(eClass), provider);
  }
  
  public EClass getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((EClass) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public EClassHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
