package de.fxdiagram.examples.ecore;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.DomainObjectProvider;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.examples.ecore.EcoreDomainObjectProvider;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.xtext.xbase.lib.Extension;

@ModelNode({ "id", "name", "provider" })
@SuppressWarnings("all")
public class EClassHandle extends DomainObjectHandleImpl {
  public EClassHandle(final EClass eClass, @Extension final EcoreDomainObjectProvider provider) {
    super(provider.getId(eClass), provider.getFqn(eClass), provider);
  }
  
  public EClass getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((EClass) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public EClassHandle() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(idProperty(), String.class);
    modelElement.addProperty(nameProperty(), String.class);
    modelElement.addProperty(providerProperty(), DomainObjectProvider.class);
  }
}
