package de.fxdiagram.examples.ecore;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.CachedDomainObjectDescriptor;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import de.fxdiagram.examples.ecore.ESuperTypeHandle;
import de.fxdiagram.examples.ecore.EcoreDomainObjectProvider;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.xbase.lib.Extension;

@ModelNode
@SuppressWarnings("all")
public class ESuperTypeDescriptor extends CachedDomainObjectDescriptor<ESuperTypeHandle> {
  public ESuperTypeDescriptor(final ESuperTypeHandle it, @Extension final EcoreDomainObjectProvider provider) {
    super(it, 
      ((provider.getId(it.getSubType()) + "=") + Integer.valueOf(it.getSubType().getEAllSuperTypes().indexOf(it.getSuperType()))), provider);
  }
  
  @Override
  public ESuperTypeHandle resolveDomainObject() {
    ESuperTypeHandle _xblockexpression = null;
    {
      final URI uri = URI.createURI(this.getId());
      final EPackage ePackage = EPackage.Registry.INSTANCE.getEPackage(uri.trimFragment().toString());
      final int posEquals = uri.fragment().indexOf("=");
      String _xifexpression = null;
      if ((posEquals == (-1))) {
        _xifexpression = uri.fragment();
      } else {
        _xifexpression = uri.fragment().substring(0, posEquals);
      }
      final String fragment = _xifexpression;
      final EObject eObject = ePackage.eResource().getEObject(fragment);
      final EClass eClass = ((EClass) eObject);
      EClass _get = eClass.getEAllSuperTypes().get(Integer.parseInt(uri.fragment().substring((posEquals + 1))));
      _xblockexpression = new ESuperTypeHandle(eClass, _get);
    }
    return _xblockexpression;
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public ESuperTypeDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
  
  public void postLoad() {
    
  }
  
  public String toString() {
    return ToString.toString(this);
  }
}
