package de.fxdiagram.examples.ecore;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.ecore.ESuperType;
import de.fxdiagram.examples.ecore.EcoreDomainObjectProvider;
import org.eclipse.xtext.xbase.lib.Extension;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class ESuperTypeHandle extends DomainObjectHandleImpl {
  public ESuperTypeHandle(final ESuperType it, @Extension final EcoreDomainObjectProvider provider) {
    super(((provider.getId(it.getSubType()) + "=") + Integer.valueOf(it.getSubType().getEAllSuperTypes().indexOf(it.getSuperType()))), 
      ((provider.getId(it.getSubType()) + "=") + Integer.valueOf(it.getSubType().getEAllSuperTypes().indexOf(it.getSuperType()))), provider);
  }
  
  public ESuperType getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((ESuperType) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public ESuperTypeHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
