package de.fxdiagram.examples.java;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.java.JavaModelProvider;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class JavaTypeHandle extends DomainObjectHandleImpl {
  public JavaTypeHandle(final Class<?> javaClass, final JavaModelProvider provider) {
    super(javaClass.getCanonicalName(), javaClass.getCanonicalName(), provider);
  }
  
  public Class<?> getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((Class<?>) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public JavaTypeHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
