package de.fxdiagram.examples.java;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectDescriptorImpl;
import de.fxdiagram.core.model.DomainObjectProvider;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.examples.java.JavaModelProvider;

@ModelNode({ "id", "name", "provider" })
@SuppressWarnings("all")
public class JavaTypeDescriptor extends DomainObjectDescriptorImpl<Class<?>> {
  public JavaTypeDescriptor(final Class<?> javaClass, final JavaModelProvider provider) {
    super(javaClass.getCanonicalName(), javaClass.getCanonicalName(), provider);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public JavaTypeDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(idProperty(), String.class);
    modelElement.addProperty(nameProperty(), String.class);
    modelElement.addProperty(providerProperty(), DomainObjectProvider.class);
  }
}
