package de.fxdiagram.examples.java;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.java.JavaModelProvider;
import de.fxdiagram.examples.java.JavaSuperType;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class JavaSuperTypeHandle extends DomainObjectHandleImpl {
  public JavaSuperTypeHandle(final JavaSuperType it, final JavaModelProvider provider) {
    super(((it.getSubType().getCanonicalName() + "->") + it.getSuperType().getCanonicalName()), 
      ((it.getSubType().getCanonicalName() + "->") + it.getSuperType().getCanonicalName()), provider);
  }
  
  public JavaSuperType getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((JavaSuperType) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public JavaSuperTypeHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
