package de.fxdiagram.examples.java;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandleImpl;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.examples.java.JavaModelProvider;
import de.fxdiagram.examples.java.JavaProperty;

@ModelNode({ "id", "key", "provider" })
@SuppressWarnings("all")
public class JavaPropertyHandle extends DomainObjectHandleImpl {
  public JavaPropertyHandle(final JavaProperty it, final JavaModelProvider provider) {
    super(((it.getType().getCanonicalName() + " ") + it.getName()), ((it.getType().getCanonicalName() + " ") + it.getName()), provider);
  }
  
  public JavaProperty getDomainObject() {
    Object _domainObject = super.getDomainObject();
    return ((JavaProperty) _domainObject);
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public JavaPropertyHandle(final ModelLoad modelLoad) {
    super(modelLoad);
  }
  
  public void populate(final ModelElement modelElement) {
    
  }
}
