package de.fxdiagram.examples.java;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectDescriptorImpl;
import de.fxdiagram.core.model.DomainObjectProvider;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.examples.java.JavaModelProvider;
import de.fxdiagram.examples.java.JavaProperty;

@ModelNode({ "id", "name", "provider" })
@SuppressWarnings("all")
public class JavaPropertyDescriptor extends DomainObjectDescriptorImpl<JavaProperty> {
  public JavaPropertyDescriptor(final JavaProperty it, final JavaModelProvider provider) {
    super(((it.getType().getCanonicalName() + " ") + it.getName()), ((it.getType().getCanonicalName() + " ") + it.getName()), provider);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public JavaPropertyDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(idProperty(), String.class);
    modelElement.addProperty(nameProperty(), String.class);
    modelElement.addProperty(providerProperty(), DomainObjectProvider.class);
  }
}
