package de.fxdiagram.core.anchors;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.XConnection;
import de.fxdiagram.core.anchors.ArrowHead;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.scene.Node;
import javafx.scene.paint.Paint;
import javafx.scene.shape.Circle;
import javafx.scene.shape.StrokeType;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@ModelNode("fill")
@SuppressWarnings("all")
public class CircleArrowHead extends ArrowHead {
  public CircleArrowHead(final XConnection connection, final double radius, final Paint stroke, final Paint fill, final boolean isSource) {
    super(connection, radius, radius, stroke, isSource);
    boolean _notEquals = (!Objects.equal(fill, null));
    if (_notEquals) {
      this.setFill(fill);
    }
    this.heightProperty().bindBidirectional(this.widthProperty());
  }
  
  public CircleArrowHead(final XConnection connection, final boolean isSource) {
    this(connection, 4, null, null, isSource);
  }
  
  @Override
  public Node createNode() {
    Circle _xblockexpression = null;
    {
      Paint _fill = this.getFill();
      boolean _equals = Objects.equal(_fill, null);
      if (_equals) {
        this.fillProperty.bind(this.getConnection().strokeProperty());
      }
      Circle _circle = new Circle();
      final Procedure1<Circle> _function = (Circle it) -> {
        it.setRadius(this.getWidth());
        double _radius = it.getRadius();
        double _minus = (-_radius);
        it.setLayoutX(_minus);
        it.setLayoutY(0);
        it.fillProperty().bind(this.fillProperty);
        it.strokeProperty().bind(this.strokeProperty());
        it.strokeWidthProperty().bind(this.getConnection().strokeWidthProperty());
        it.opacityProperty().bind(this.getConnection().opacityProperty());
        it.setStrokeType(StrokeType.CENTERED);
      };
      _xblockexpression = ObjectExtensions.<Circle>operator_doubleArrow(_circle, _function);
    }
    return _xblockexpression;
  }
  
  @Override
  public double getLineCut() {
    double _width = this.getWidth();
    double _strokeWidth = this.getConnection().getStrokeWidth();
    return (_width + _strokeWidth);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public CircleArrowHead() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
    modelElement.addProperty(fillProperty, Paint.class);
  }
  
  public void postLoad() {
    
  }
  
  public String toString() {
    return ToString.toString(this);
  }
  
  private SimpleObjectProperty<Paint> fillProperty = new SimpleObjectProperty<Paint>(this, "fill");
  
  public Paint getFill() {
    return this.fillProperty.get();
  }
  
  public void setFill(final Paint fill) {
    this.fillProperty.set(fill);
  }
  
  public ObjectProperty<Paint> fillProperty() {
    return this.fillProperty;
  }
}
