package de.fxdiagram.core.anchors;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.XConnection;
import de.fxdiagram.core.anchors.ArrowHead;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import java.util.Collections;
import javafx.collections.ObservableList;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.paint.Paint;
import javafx.scene.shape.Polyline;
import javafx.scene.shape.StrokeType;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@ModelNode
@SuppressWarnings("all")
public class LineArrowHead extends ArrowHead {
  public LineArrowHead(final XConnection connection, final double width, final double height, final Paint stroke, final boolean isSource) {
    super(connection, width, height, stroke, isSource);
  }
  
  public LineArrowHead(final XConnection connection, final boolean isSource) {
    this(connection, 7, 10, null, isSource);
  }
  
  @Override
  public Node createNode() {
    Group _group = new Group();
    final Procedure1<Group> _function = (Group it) -> {
      ObservableList<Node> _children = it.getChildren();
      Polyline _polyline = new Polyline();
      final Procedure1<Polyline> _function_1 = (Polyline it_1) -> {
        double _height = this.getHeight();
        double _multiply = ((-0.5) * _height);
        double _width = this.getWidth();
        double _height_1 = this.getHeight();
        double _multiply_1 = (0.5 * _height_1);
        it_1.getPoints().setAll(Collections.<Double>unmodifiableList(CollectionLiterals.<Double>newArrayList(Double.valueOf(0.0), Double.valueOf(_multiply), Double.valueOf(_width), Double.valueOf(0.0), Double.valueOf(0.0), Double.valueOf(_multiply_1))));
        it_1.strokeProperty().bind(this.strokeProperty());
        it_1.strokeWidthProperty().bind(this.getConnection().strokeWidthProperty());
        it_1.opacityProperty().bind(this.getConnection().opacityProperty());
        it_1.setStrokeType(StrokeType.CENTERED);
      };
      Polyline _doubleArrow = ObjectExtensions.<Polyline>operator_doubleArrow(_polyline, _function_1);
      _children.add(_doubleArrow);
      ObservableList<Node> _children_1 = it.getChildren();
      Polyline _polyline_1 = new Polyline();
      final Procedure1<Polyline> _function_2 = (Polyline it_1) -> {
        double _width = this.getWidth();
        double _strokeWidth = this.getConnection().getStrokeWidth();
        double _minus = (_width - _strokeWidth);
        it_1.getPoints().setAll(Collections.<Double>unmodifiableList(CollectionLiterals.<Double>newArrayList(Double.valueOf(0.0), Double.valueOf(0.0), Double.valueOf(_minus), Double.valueOf(0.0))));
        it_1.strokeProperty().bind(this.strokeProperty());
        it_1.strokeWidthProperty().bind(this.getConnection().strokeWidthProperty());
        it_1.opacityProperty().bind(this.getConnection().opacityProperty());
        it_1.setStrokeType(StrokeType.CENTERED);
      };
      Polyline _doubleArrow_1 = ObjectExtensions.<Polyline>operator_doubleArrow(_polyline_1, _function_2);
      _children_1.add(_doubleArrow_1);
    };
    return ObjectExtensions.<Group>operator_doubleArrow(_group, _function);
  }
  
  @Override
  public double getLineCut() {
    double _width = this.getWidth();
    double _strokeWidth = this.getConnection().getStrokeWidth();
    return (_width + _strokeWidth);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public LineArrowHead() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
  
  public void postLoad() {
    
  }
  
  public String toString() {
    return ToString.toString(this);
  }
}
