package de.fxdiagram.core.model;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandle;
import de.fxdiagram.core.model.ModelElementImpl;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

@ModelNode({ "key" })
@SuppressWarnings("all")
public class StringHandle implements DomainObjectHandle {
  public StringHandle(final String key) {
    this.setKey(key);
  }
  
  public String getId() {
    return this.getKey();
  }
  
  public Object getDomainObject() {
    return this.getKey();
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public StringHandle() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(keyProperty, String.class);
  }
  
  private SimpleStringProperty keyProperty = new SimpleStringProperty(this, "key",_initKey());
  
  private static final String _initKey() {
    return null;
  }
  
  public String getKey() {
    return this.keyProperty.get();
  }
  
  public void setKey(final String key) {
    this.keyProperty.set(key);
  }
  
  public StringProperty keyProperty() {
    return this.keyProperty;
  }
}
