package de.fxdiagram.core.model;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectDescriptor;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;

/**
 * A {@link DomainObjectDescriptor} that has a simple {@link String} as domain object.
 * Mainly used in the examples.
 */
@ModelNode("name")
@SuppressWarnings("all")
public class StringDescriptor implements DomainObjectDescriptor {
  public StringDescriptor(final String name) {
    this.nameProperty.set(name);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public StringDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(nameProperty, String.class);
  }
  
  public String toString() {
    return ToString.toString(this);
  }
  
  private ReadOnlyStringWrapper nameProperty = new ReadOnlyStringWrapper(this, "name",_initName());
  
  private static final String _initName() {
    return null;
  }
  
  public String getName() {
    return this.nameProperty.get();
  }
  
  public ReadOnlyStringProperty nameProperty() {
    return this.nameProperty.getReadOnlyProperty();
  }
}
