package de.fxdiagram.core.model;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectHandle;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;

@ModelNode({ "key", "provider" })
@SuppressWarnings("all")
public class StringHandle implements DomainObjectHandle {
  public StringHandle(final String key) {
    this.setKey(key);
  }
  
  public void setKey(final String key) {
    String _key = this.getKey();
    boolean _notEquals = (!Objects.equal(_key, null));
    if (_notEquals) {
      throw new IllegalStateException("Cannot reset the key on a StringHandle");
    }
    this.keyProperty.set(key);
  }
  
  public String getId() {
    return this.getKey();
  }
  
  public Object getDomainObject() {
    return this.getKey();
  }
  
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public StringHandle(final ModelLoad modelLoad) {
  }
  
  public void populate(final ModelElement modelElement) {
    modelElement.addProperty(keyProperty, String.class);
  }
  
  private ReadOnlyStringWrapper keyProperty = new ReadOnlyStringWrapper(this, "key",_initKey());
  
  private static final String _initKey() {
    return null;
  }
  
  public String getKey() {
    return this.keyProperty.get();
  }
  
  public ReadOnlyStringProperty keyProperty() {
    return this.keyProperty.getReadOnlyProperty();
  }
}
