package de.fxdiagram.core.model;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElement;
import de.fxdiagram.core.model.ModelLoad;
import de.fxdiagram.core.model.TestEnum;
import de.fxdiagram.core.model.XModelProvider;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

@ModelNode({ "testEnum" })
@SuppressWarnings("all")
public class TestBean implements XModelProvider {
  /**
   * Automatically generated by @ModelNode. Used in model deserialization.
   */
  public TestBean(final ModelLoad modelLoad) {
  }
  
  /**
   * Automatically generated by @ModelNode
   */
  public TestBean() {
  }
  
  public void populate(final ModelElement modelElement) {
    modelElement.addProperty(testEnumProperty, TestEnum.class);
  }
  
  private SimpleObjectProperty<TestEnum> testEnumProperty = new SimpleObjectProperty<TestEnum>(this, "testEnum");
  
  public TestEnum getTestEnum() {
    return this.testEnumProperty.get();
  }
  
  public void setTestEnum(final TestEnum testEnum) {
    this.testEnumProperty.set(testEnum);
  }
  
  public ObjectProperty<TestEnum> testEnumProperty() {
    return this.testEnumProperty;
  }
}
