package de.fxdiagram.mapping.shapes;

import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.XConnection;
import de.fxdiagram.core.model.DomainObjectDescriptor;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.mapping.IMappedElementDescriptor;
import de.fxdiagram.mapping.behavior.ConnectionDirtyStateBehavior;

/**
 * Base implementation for a {@link XConnection} that belongs to an {@link IMappedElementDescriptor}.
 * 
 * If the descriptor is an {@link AbstractXtextDescriptor}, members are automatically injected using
 * the Xtext language's injector.
 */
@ModelNode
@SuppressWarnings("all")
public class BaseConnection<T extends Object> extends XConnection {
  public BaseConnection(final IMappedElementDescriptor<T> descriptor) {
    super(descriptor);
  }
  
  @Override
  public DomainObjectDescriptor getDomainObject() {
    DomainObjectDescriptor _domainObject = super.getDomainObject();
    return ((IMappedElementDescriptor<T>) _domainObject);
  }
  
  @Override
  public void doActivate() {
    super.doActivate();
    ConnectionDirtyStateBehavior<Object> _connectionDirtyStateBehavior = new ConnectionDirtyStateBehavior<Object>(this);
    this.addBehavior(_connectionDirtyStateBehavior);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public BaseConnection() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
}
