package de.fxdiagram.eclipse.xtext;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.eclipse.xtext.AbstractXtextDescriptor;
import de.fxdiagram.eclipse.xtext.XtextDomainObjectProvider;
import de.fxdiagram.eclipse.xtext.ids.XtextEObjectID;
import java.util.NoSuchElementException;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.ReadOnlyObjectWrapper;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.ui.IEditorPart;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.util.concurrent.IUnitOfWork;
import org.eclipse.xtext.xbase.lib.Functions.Function1;

@ModelNode("elementID")
@SuppressWarnings("all")
public class XtextEObjectDescriptor<T extends EObject> extends AbstractXtextDescriptor<T> {
  public XtextEObjectDescriptor(final XtextEObjectID elementID, final String mappingConfigID, final String mappingID) {
    super(mappingConfigID, mappingID);
    this.elementIDProperty.set(elementID);
  }
  
  @Override
  public <U extends Object> U withDomainObject(final Function1<? super T, ? extends U> lambda) {
    U _xblockexpression = null;
    {
      final IEditorPart editor = this.getProvider().getCachedEditor(this.getElementID(), false, false);
      U _xifexpression = null;
      if ((editor instanceof XtextEditor)) {
        final IUnitOfWork<U, XtextResource> _function = (XtextResource it) -> {
          U _xblockexpression_1 = null;
          {
            final EObject element = this.getElementID().resolve(it.getResourceSet());
            _xblockexpression_1 = lambda.apply(((T) element));
          }
          return _xblockexpression_1;
        };
        _xifexpression = ((XtextEditor)editor).getDocument().<U>readOnly(_function);
      } else {
        XtextEObjectID _elementID = this.getElementID();
        String _plus = ("Cannot open an Xtext editor for " + _elementID);
        throw new NoSuchElementException(_plus);
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }
  
  @Override
  public Object openInEditor(final boolean select) {
    return this.getProvider().getCachedEditor(this.getElementID(), select, select);
  }
  
  @Override
  public String getName() {
    String _elvis = null;
    QualifiedName _qualifiedName = this.getElementID().getQualifiedName();
    String _lastSegment = null;
    if (_qualifiedName!=null) {
      _lastSegment=_qualifiedName.getLastSegment();
    }
    if (_lastSegment != null) {
      _elvis = _lastSegment;
    } else {
      _elvis = "<unnamed>";
    }
    return _elvis;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof XtextEObjectDescriptor<?>)) {
      return (super.equals(obj) && Objects.equal(this.getElementID(), ((XtextEObjectDescriptor<?>)obj).getElementID()));
    } else {
      return false;
    }
  }
  
  @Override
  public int hashCode() {
    int _hashCode = super.hashCode();
    int _hashCode_1 = this.getElementID().hashCode();
    int _multiply = (17 * _hashCode_1);
    return (_hashCode + _multiply);
  }
  
  @Override
  protected IResourceServiceProvider getResourceServiceProvider() {
    return this.getElementID().getResourceServiceProvider();
  }
  
  @Override
  public String toString() {
    XtextDomainObjectProvider _provider = this.getProvider();
    String _string = this.getElementID().toString();
    return (_provider + _string);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public XtextEObjectDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
    modelElement.addProperty(elementIDProperty, XtextEObjectID.class);
  }
  
  public void postLoad() {
    
  }
  
  private ReadOnlyObjectWrapper<XtextEObjectID> elementIDProperty = new ReadOnlyObjectWrapper<XtextEObjectID>(this, "elementID");
  
  public XtextEObjectID getElementID() {
    return this.elementIDProperty.get();
  }
  
  public ReadOnlyObjectProperty<XtextEObjectID> elementIDProperty() {
    return this.elementIDProperty.getReadOnlyProperty();
  }
}
