package de.fxdiagram.xtext.glue;

import com.google.common.base.Objects;
import com.google.inject.Provider;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.DomainObjectDescriptor;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.xtext.glue.XtextDomainObjectProvider;
import de.fxdiagram.xtext.glue.mapping.AbstractMapping;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.ui.IEditorPart;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.ui.editor.IURIEditorOpener;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.shared.Access;
import org.eclipse.xtext.util.concurrent.IUnitOfWork;
import org.eclipse.xtext.xbase.lib.Functions.Function1;

@ModelNode({ "provider", "uri", "fqn", "mapping" })
@SuppressWarnings("all")
public class XtextDomainObjectDescriptor<ECLASS extends Object> implements DomainObjectDescriptor {
  public XtextDomainObjectDescriptor(final String uri, final String fqn, final AbstractMapping<ECLASS> mapping, final XtextDomainObjectProvider provider) {
    this.uriProperty.set(uri);
    this.fqnProperty.set(fqn);
    this.providerProperty.set(provider);
    this.mappingProperty.set(mapping);
  }
  
  public String getName() {
    return this.getFqn();
  }
  
  public String getId() {
    return this.getFqn();
  }
  
  public <T extends Object> T withDomainObject(final Function1<? super ECLASS,? extends T> lambda) {
    T _xblockexpression = null;
    {
      String _uri = this.getUri();
      final URI uriAsURI = URI.createURI(_uri);
      final IEditorPart editor = this.revealInEditor();
      T _xifexpression = null;
      if ((editor instanceof XtextEditor)) {
        IXtextDocument _document = ((XtextEditor)editor).getDocument();
        final IUnitOfWork<T,XtextResource> _function = new IUnitOfWork<T,XtextResource>() {
          public T exec(final XtextResource it) throws Exception {
            ResourceSet _resourceSet = it.getResourceSet();
            EObject _eObject = _resourceSet.getEObject(uriAsURI, true);
            return lambda.apply(((ECLASS) _eObject));
          }
        };
        _xifexpression = _document.<T>readOnly(_function);
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }
  
  public boolean equals(final Object obj) {
    boolean _xifexpression = false;
    if ((obj instanceof XtextDomainObjectDescriptor<?>)) {
      String _uri = ((XtextDomainObjectDescriptor<?>)obj).getUri();
      String _uri_1 = this.getUri();
      _xifexpression = Objects.equal(_uri, _uri_1);
    } else {
      _xifexpression = false;
    }
    return _xifexpression;
  }
  
  public int hashCode() {
    String _uri = this.getUri();
    int _hashCode = _uri.hashCode();
    return (103 * _hashCode);
  }
  
  public IEditorPart revealInEditor() {
    Provider<IURIEditorOpener> _iURIEditorOpener = Access.getIURIEditorOpener();
    IURIEditorOpener _get = _iURIEditorOpener.get();
    String _uri = this.getUri();
    URI _createURI = URI.createURI(_uri);
    return _get.open(_createURI, true);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public XtextDomainObjectDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(providerProperty, XtextDomainObjectProvider.class);
    modelElement.addProperty(uriProperty, String.class);
    modelElement.addProperty(fqnProperty, String.class);
    modelElement.addProperty(mappingProperty, AbstractMapping.class);
  }
  
  private ReadOnlyObjectWrapper<XtextDomainObjectProvider> providerProperty = new ReadOnlyObjectWrapper<XtextDomainObjectProvider>(this, "provider");
  
  public XtextDomainObjectProvider getProvider() {
    return this.providerProperty.get();
  }
  
  public ReadOnlyObjectProperty<XtextDomainObjectProvider> providerProperty() {
    return this.providerProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyStringWrapper fqnProperty = new ReadOnlyStringWrapper(this, "fqn");
  
  public String getFqn() {
    return this.fqnProperty.get();
  }
  
  public ReadOnlyStringProperty fqnProperty() {
    return this.fqnProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyStringWrapper uriProperty = new ReadOnlyStringWrapper(this, "uri");
  
  public String getUri() {
    return this.uriProperty.get();
  }
  
  public ReadOnlyStringProperty uriProperty() {
    return this.uriProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyObjectWrapper<AbstractMapping<ECLASS>> mappingProperty = new ReadOnlyObjectWrapper<AbstractMapping<ECLASS>>(this, "mapping");
  
  public AbstractMapping<ECLASS> getMapping() {
    return this.mappingProperty.get();
  }
  
  public ReadOnlyObjectProperty<AbstractMapping<ECLASS>> mappingProperty() {
    return this.mappingProperty.getReadOnlyProperty();
  }
}
