package de.fxdiagram.mapping;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.mapping.AbstractMapping;
import de.fxdiagram.mapping.IMappedElementDescriptor;
import de.fxdiagram.mapping.IMappedElementDescriptorProvider;
import de.fxdiagram.mapping.XDiagramConfig;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;

/**
 * Base implementation of {@link IMappedElementDescriptor}.
 */
@ModelNode({ "provider", "mappingConfigID", "mappingID" })
@SuppressWarnings("all")
public abstract class AbstractMappedElementDescriptor<T extends Object> implements IMappedElementDescriptor<T> {
  private AbstractMapping<T> mapping;
  
  public AbstractMappedElementDescriptor(final String mappingConfigID, final String mappingID, final IMappedElementDescriptorProvider provider) {
    this.providerProperty.set(provider);
    this.mappingConfigIDProperty.set(mappingConfigID);
    this.mappingIDProperty.set(mappingID);
  }
  
  @Override
  public AbstractMapping<T> getMapping() {
    AbstractMapping<T> _xblockexpression = null;
    {
      boolean _equals = Objects.equal(this.mapping, null);
      if (_equals) {
        XDiagramConfig.Registry _instance = XDiagramConfig.Registry.getInstance();
        String _mappingConfigID = this.getMappingConfigID();
        final XDiagramConfig config = _instance.getConfigByID(_mappingConfigID);
        String _mappingID = this.getMappingID();
        AbstractMapping<?> _mappingByID = config.getMappingByID(_mappingID);
        this.mapping = ((AbstractMapping<T>) _mappingByID);
      }
      _xblockexpression = this.mapping;
    }
    return _xblockexpression;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof AbstractMappedElementDescriptor<?>)) {
      boolean _and = false;
      boolean _and_1 = false;
      IMappedElementDescriptorProvider _provider = this.getProvider();
      IMappedElementDescriptorProvider _provider_1 = ((AbstractMappedElementDescriptor<?>)obj).getProvider();
      boolean _equals = Objects.equal(_provider, _provider_1);
      if (!_equals) {
        _and_1 = false;
      } else {
        String _mappingConfigID = this.getMappingConfigID();
        String _mappingConfigID_1 = ((AbstractMappedElementDescriptor<?>)obj).getMappingConfigID();
        boolean _equals_1 = Objects.equal(_mappingConfigID, _mappingConfigID_1);
        _and_1 = _equals_1;
      }
      if (!_and_1) {
        _and = false;
      } else {
        String _mappingID = this.getMappingID();
        String _mappingID_1 = ((AbstractMappedElementDescriptor<?>)obj).getMappingID();
        boolean _equals_2 = Objects.equal(_mappingID, _mappingID_1);
        _and = _equals_2;
      }
      return _and;
    } else {
      return false;
    }
  }
  
  @Override
  public int hashCode() {
    String _mappingConfigID = this.getMappingConfigID();
    int _hashCode = _mappingConfigID.hashCode();
    int _multiply = (31 * _hashCode);
    String _mappingID = this.getMappingID();
    int _hashCode_1 = _mappingID.hashCode();
    int _multiply_1 = (37 * _hashCode_1);
    int _plus = (_multiply + _multiply_1);
    IMappedElementDescriptorProvider _provider = this.getProvider();
    int _hashCode_2 = _provider.hashCode();
    int _multiply_2 = (79 * _hashCode_2);
    return (_plus + _multiply_2);
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public AbstractMappedElementDescriptor() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(providerProperty, IMappedElementDescriptorProvider.class);
    modelElement.addProperty(mappingConfigIDProperty, String.class);
    modelElement.addProperty(mappingIDProperty, String.class);
  }
  
  private ReadOnlyStringWrapper mappingConfigIDProperty = new ReadOnlyStringWrapper(this, "mappingConfigID");
  
  public String getMappingConfigID() {
    return this.mappingConfigIDProperty.get();
  }
  
  public ReadOnlyStringProperty mappingConfigIDProperty() {
    return this.mappingConfigIDProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyStringWrapper mappingIDProperty = new ReadOnlyStringWrapper(this, "mappingID");
  
  public String getMappingID() {
    return this.mappingIDProperty.get();
  }
  
  public ReadOnlyStringProperty mappingIDProperty() {
    return this.mappingIDProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyObjectWrapper<IMappedElementDescriptorProvider> providerProperty = new ReadOnlyObjectWrapper<IMappedElementDescriptorProvider>(this, "provider");
  
  public IMappedElementDescriptorProvider getProvider() {
    return this.providerProperty.get();
  }
  
  public ReadOnlyObjectProperty<IMappedElementDescriptorProvider> providerProperty() {
    return this.providerProperty.getReadOnlyProperty();
  }
}
