package de.fxdiagram.eclipse.xtext.ids;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import de.fxdiagram.core.model.XModelProvider;
import de.fxdiagram.eclipse.xtext.ids.XtextEObjectID;
import java.util.NoSuchElementException;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@ModelNode({ "eClassURIAsString", "uriAsString" })
@SuppressWarnings("all")
public abstract class AbstractXtextEObjectID implements XtextEObjectID, XModelProvider {
  private EClass eClass;
  
  private URI uri;
  
  public AbstractXtextEObjectID(final EClass eClass, final URI elementURI) {
    this.uri = elementURI;
    this.uriAsStringProperty.set(elementURI.toString());
    this.eClass = eClass;
    this.eClassURIAsStringProperty.set(EcoreUtil.getURI(eClass).toString());
  }
  
  @Override
  public URI getURI() {
    URI _elvis = null;
    if (this.uri != null) {
      _elvis = this.uri;
    } else {
      _elvis = this.uri = URI.createURI(this.getUriAsString());
    }
    return _elvis;
  }
  
  @Override
  public EClass getEClass() {
    EClass _elvis = null;
    if (this.eClass != null) {
      _elvis = this.eClass;
    } else {
      _elvis = (this.eClass = this.getEClass(this.getEClassURIAsString()));
    }
    return _elvis;
  }
  
  protected EClass getEClass(final String uriAsString) {
    EClass _xblockexpression = null;
    {
      if ((uriAsString == null)) {
        return null;
      }
      final URI eClassURI = URI.createURI(uriAsString);
      final EPackage ePackage = EPackage.Registry.INSTANCE.getEPackage(eClassURI.trimFragment().toString());
      if ((ePackage == null)) {
        URI _trimFragment = eClassURI.trimFragment();
        String _plus = ("Cannot find EPackage " + _trimFragment);
        throw new NoSuchElementException(_plus);
      }
      EObject _eObject = ePackage.eResource().getEObject(eClassURI.fragment());
      this.eClass = ((EClass) _eObject);
      if ((this.eClass == null)) {
        throw new NoSuchElementException(("Cannot find EClass " + eClassURI));
      }
      _xblockexpression = this.eClass;
    }
    return _xblockexpression;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof AbstractXtextEObjectID)) {
      return (Objects.equal(((AbstractXtextEObjectID)obj).getURI().trimFragment(), this.getURI().trimFragment()) && Objects.equal(((AbstractXtextEObjectID)obj).getEClass(), this.getEClass()));
    } else {
      return false;
    }
  }
  
  @Override
  public int hashCode() {
    int _hashCode = this.getURI().trimFragment().hashCode();
    int _multiply = (_hashCode * 29);
    int _hashCode_1 = this.getEClass().hashCode();
    int _multiply_1 = (_hashCode_1 * 173);
    return (_multiply + _multiply_1);
  }
  
  @Override
  public IResourceServiceProvider getResourceServiceProvider() {
    return IResourceServiceProvider.Registry.INSTANCE.getResourceServiceProvider(this.getURI());
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public AbstractXtextEObjectID() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    modelElement.addProperty(eClassURIAsStringProperty, String.class);
    modelElement.addProperty(uriAsStringProperty, String.class);
  }
  
  public void postLoad() {
    
  }
  
  public String toString() {
    return ToString.toString(this);
  }
  
  private ReadOnlyStringWrapper eClassURIAsStringProperty = new ReadOnlyStringWrapper(this, "eClassURIAsString");
  
  public String getEClassURIAsString() {
    return this.eClassURIAsStringProperty.get();
  }
  
  public ReadOnlyStringProperty eClassURIAsStringProperty() {
    return this.eClassURIAsStringProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyStringWrapper uriAsStringProperty = new ReadOnlyStringWrapper(this, "uriAsString");
  
  public String getUriAsString() {
    return this.uriAsStringProperty.get();
  }
  
  public ReadOnlyStringProperty uriAsStringProperty() {
    return this.uriAsStringProperty.getReadOnlyProperty();
  }
}
