package de.fxdiagram.eclipse.xtext.ids;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.eclipse.xtext.ids.AbstractXtextEObjectID;
import de.fxdiagram.eclipse.xtext.ids.XtextEObjectID;
import java.util.NoSuchElementException;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.beans.property.ReadOnlyStringWrapper;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.naming.QualifiedName;

@ModelNode({ "parentID", "relativeFragment" })
@SuppressWarnings("all")
public class RelativeXtextEObjectID extends AbstractXtextEObjectID {
  public RelativeXtextEObjectID(final XtextEObjectID parentID, final EClass eClass, final URI elementURI, final String relativeFragment) {
    super(eClass, elementURI);
    this.parentIDProperty.set(parentID);
    this.relativeFragmentProperty.set(relativeFragment);
  }
  
  @Override
  public QualifiedName getQualifiedName() {
    return null;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof RelativeXtextEObjectID)) {
      boolean _and = false;
      boolean _and_1 = false;
      boolean _equals = super.equals(obj);
      if (!_equals) {
        _and_1 = false;
      } else {
        XtextEObjectID _parentID = ((RelativeXtextEObjectID)obj).getParentID();
        XtextEObjectID _parentID_1 = this.getParentID();
        boolean _equals_1 = Objects.equal(_parentID, _parentID_1);
        _and_1 = _equals_1;
      }
      if (!_and_1) {
        _and = false;
      } else {
        String _relativeFragment = ((RelativeXtextEObjectID)obj).getRelativeFragment();
        String _relativeFragment_1 = this.getRelativeFragment();
        boolean _equals_2 = Objects.equal(_relativeFragment, _relativeFragment_1);
        _and = _equals_2;
      }
      return _and;
    } else {
      return false;
    }
  }
  
  @Override
  public int hashCode() {
    XtextEObjectID _parentID = this.getParentID();
    int _hashCode = _parentID.hashCode();
    int _multiply = (461 * _hashCode);
    String _relativeFragment = this.getRelativeFragment();
    int _hashCode_1 = _relativeFragment.hashCode();
    int _multiply_1 = (503 * _hashCode_1);
    int _plus = (_multiply + _multiply_1);
    int _hashCode_2 = super.hashCode();
    int _multiply_2 = (101 * _hashCode_2);
    return (_plus + _multiply_2);
  }
  
  @Override
  public String toString() {
    String _xblockexpression = null;
    {
      XtextEObjectID _parentID = this.getParentID();
      _parentID.toString();
      String _relativeFragment = this.getRelativeFragment();
      _xblockexpression = ("->" + _relativeFragment);
    }
    return _xblockexpression;
  }
  
  @Override
  public EObject resolve(final ResourceSet resourceSet) {
    XtextEObjectID _parentID = this.getParentID();
    final EObject parent = _parentID.resolve(resourceSet);
    String _xifexpression = null;
    String _relativeFragment = this.getRelativeFragment();
    boolean _startsWith = _relativeFragment.startsWith("#");
    if (_startsWith) {
      _xifexpression = this.getRelativeFragment();
    } else {
      URI _uRI = EcoreUtil.getURI(parent);
      String _fragment = _uRI.fragment();
      String _relativeFragment_1 = this.getRelativeFragment();
      _xifexpression = (_fragment + _relativeFragment_1);
    }
    final String elementFragment = _xifexpression;
    Resource _eResource = parent.eResource();
    final EObject element = _eResource.getEObject(elementFragment);
    boolean _or = false;
    boolean _equals = Objects.equal(element, null);
    if (_equals) {
      _or = true;
    } else {
      boolean _eIsProxy = element.eIsProxy();
      _or = _eIsProxy;
    }
    if (_or) {
      String _string = this.toString();
      String _plus = ("Could not resolve element " + _string);
      throw new NoSuchElementException(_plus);
    }
    EClass _eClass = this.getEClass();
    boolean _isInstance = _eClass.isInstance(element);
    boolean _not = (!_isInstance);
    if (_not) {
      EClass _eClass_1 = this.getEClass();
      String _name = _eClass_1.getName();
      String _plus_1 = ("Expected " + _name);
      String _plus_2 = (_plus_1 + " but got ");
      EClass _eClass_2 = element.eClass();
      String _name_1 = _eClass_2.getName();
      String _plus_3 = (_plus_2 + _name_1);
      throw new NoSuchElementException(_plus_3);
    }
    return element;
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public RelativeXtextEObjectID() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
    modelElement.addProperty(parentIDProperty, XtextEObjectID.class);
    modelElement.addProperty(relativeFragmentProperty, String.class);
  }
  
  private ReadOnlyObjectWrapper<XtextEObjectID> parentIDProperty = new ReadOnlyObjectWrapper<XtextEObjectID>(this, "parentID");
  
  public XtextEObjectID getParentID() {
    return this.parentIDProperty.get();
  }
  
  public ReadOnlyObjectProperty<XtextEObjectID> parentIDProperty() {
    return this.parentIDProperty.getReadOnlyProperty();
  }
  
  private ReadOnlyStringWrapper relativeFragmentProperty = new ReadOnlyStringWrapper(this, "relativeFragment");
  
  public String getRelativeFragment() {
    return this.relativeFragmentProperty.get();
  }
  
  public ReadOnlyStringProperty relativeFragmentProperty() {
    return this.relativeFragmentProperty.getReadOnlyProperty();
  }
}
