package de.fxdiagram.eclipse.xtext.ids;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.eclipse.xtext.ids.AbstractXtextEObjectID;
import java.util.NoSuchElementException;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.naming.QualifiedName;

@ModelNode
@SuppressWarnings("all")
public class UnnamedXtextEObjectID extends AbstractXtextEObjectID {
  public UnnamedXtextEObjectID(final EClass eClass, final URI elementURI) {
    super(eClass, elementURI);
  }
  
  @Override
  public QualifiedName getQualifiedName() {
    return null;
  }
  
  @Override
  public EObject resolve(final ResourceSet resourceSet) {
    URI _uRI = this.getURI();
    final EObject element = resourceSet.getEObject(_uRI, true);
    boolean _or = false;
    boolean _equals = Objects.equal(element, null);
    if (_equals) {
      _or = true;
    } else {
      boolean _eIsProxy = element.eIsProxy();
      _or = _eIsProxy;
    }
    if (_or) {
      URI _uRI_1 = this.getURI();
      String _plus = ("Could not resolve " + _uRI_1);
      throw new NoSuchElementException(_plus);
    }
    EClass _eClass = this.getEClass();
    boolean _isInstance = _eClass.isInstance(element);
    boolean _not = (!_isInstance);
    if (_not) {
      EClass _eClass_1 = this.getEClass();
      String _name = _eClass_1.getName();
      String _plus_1 = ("Expected " + _name);
      String _plus_2 = (_plus_1 + " but got ");
      EClass _eClass_2 = element.eClass();
      String _name_1 = _eClass_2.getName();
      String _plus_3 = (_plus_2 + _name_1);
      throw new NoSuchElementException(_plus_3);
    }
    return element;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof UnnamedXtextEObjectID)) {
      boolean _and = false;
      boolean _equals = super.equals(obj);
      if (!_equals) {
        _and = false;
      } else {
        URI _uRI = this.getURI();
        URI _uRI_1 = ((UnnamedXtextEObjectID)obj).getURI();
        boolean _equals_1 = Objects.equal(_uRI, _uRI_1);
        _and = _equals_1;
      }
      return _and;
    } else {
      return false;
    }
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public UnnamedXtextEObjectID() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
}
