package de.fxdiagram.eclipse.xtext.ids;

import com.google.common.base.Objects;
import de.fxdiagram.annotations.properties.ModelNode;
import de.fxdiagram.core.model.ModelElementImpl;
import de.fxdiagram.core.model.ToString;
import de.fxdiagram.eclipse.xtext.ids.AbstractXtextEObjectID;
import java.util.NoSuchElementException;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.IResourceDescriptions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

@ModelNode
@SuppressWarnings("all")
public class UnnamedXtextEObjectID extends AbstractXtextEObjectID {
  public UnnamedXtextEObjectID(final EClass eClass, final URI elementURI) {
    super(eClass, elementURI);
  }
  
  @Override
  public QualifiedName getQualifiedName() {
    return null;
  }
  
  @Override
  public IEObjectDescription findInIndex(final IResourceDescriptions index) {
    IEObjectDescription _xblockexpression = null;
    {
      final IResourceDescription resourceDescription = index.getResourceDescription(this.getURI().trimFragment());
      final Function1<IEObjectDescription, Boolean> _function = (IEObjectDescription it) -> {
        URI _uRI = this.getURI();
        URI _eObjectURI = it.getEObjectURI();
        return Boolean.valueOf(Objects.equal(_uRI, _eObjectURI));
      };
      _xblockexpression = IterableExtensions.<IEObjectDescription>findFirst(resourceDescription.getExportedObjectsByType(this.getEClass()), _function);
    }
    return _xblockexpression;
  }
  
  @Override
  public EObject resolve(final ResourceSet resourceSet) {
    final EObject element = resourceSet.getEObject(this.getURI(), true);
    if (((element == null) || element.eIsProxy())) {
      URI _uRI = this.getURI();
      String _plus = ("Could not resolve " + _uRI);
      throw new NoSuchElementException(_plus);
    }
    boolean _isInstance = this.getEClass().isInstance(element);
    boolean _not = (!_isInstance);
    if (_not) {
      String _name = this.getEClass().getName();
      String _plus_1 = ("Expected " + _name);
      String _plus_2 = (_plus_1 + " but got ");
      String _name_1 = element.eClass().getName();
      String _plus_3 = (_plus_2 + _name_1);
      throw new NoSuchElementException(_plus_3);
    }
    return element;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if ((obj instanceof UnnamedXtextEObjectID)) {
      return (super.equals(obj) && Objects.equal(this.getURI(), ((UnnamedXtextEObjectID)obj).getURI()));
    } else {
      return false;
    }
  }
  
  /**
   * Automatically generated by @ModelNode. Needed for deserialization.
   */
  public UnnamedXtextEObjectID() {
  }
  
  public void populate(final ModelElementImpl modelElement) {
    super.populate(modelElement);
  }
  
  public void postLoad() {
    
  }
  
  public String toString() {
    return ToString.toString(this);
  }
}
